export interface BwIllustrationItem {
  id: string
  title: string
  category: 'SELF PHOTO' | 'BARENG TEMAN' | 'PHOTOBOOTH' | 'CREATIVE SHOOT'
  subtitle: string
  tag: string
  lens: string
  iso: string
  shutter: string
  desc: string
  badge: string
  imageUrl: string
  type: string
}

// 2D Black & White Character Poses - Gaya gambar 2D tinta tegas dengan perspektif dinamis dan kedalaman studio
export const BW_HERO_POSES = [
  {
    id: 'pose-1',
    name: 'Self Photo Studio Solo',
    tag: 'SELF PHOTO / 001',
    lens: '35mm Wide Studio',
    iso: 'ISO 100',
    shutter: '1/250s',
    sub: 'Pose santai pemuda memegang remote shutter nirkabel dengan sudut perspektif kamera studio yang dinamis',
    imageUrl: '/images/self_photo.jpg',
    type: 'self_photo',
  },
  {
    id: 'pose-2',
    name: 'Bareng Teman & Sahabat',
    tag: 'BARENG TEMAN / 002',
    lens: '28mm Wide-Angle',
    iso: 'ISO 200',
    shutter: '1/200s',
    sub: 'Pose ceria dua sahabat berdampingan di studio luas dengan senyum candid, tanda peace sign, dan perspektif ruang mendalam',
    imageUrl: '/images/bareng_teman.jpg',
    type: 'bareng_teman',
  },
  {
    id: 'pose-3',
    name: 'Photobooth Bilik Seru',
    tag: 'PHOTOBOOTH / 003',
    lens: '24mm Photobooth Lens',
    iso: 'ISO 400',
    shutter: '1/320s',
    sub: 'Keseruan tiga sahabat di dalam bilik photobooth dengan kacamata retro, photostrip instan, dan sudut pandang wide-angle',
    imageUrl: '/images/photobooth.jpg',
    type: 'photobooth',
  },
  {
    id: 'pose-4',
    name: 'Creative Shoot Artistik',
    tag: 'CREATIVE SHOOT / 004',
    lens: '35mm High-Angle Studio',
    iso: 'ISO 100',
    shutter: '1/500s',
    sub: 'Potret editorial model duduk elegan di kubus studio dengan sudut pandang high-angle dan tata cahaya softbox profesional',
    imageUrl: '/images/creative_shoot.jpg',
    type: 'creative_shoot',
  },
  {
    id: 'pose-5',
    name: 'Pasangan & Pre-Wedding',
    tag: 'PASANGAN / 005',
    lens: '50mm Studio Portrait',
    iso: 'ISO 100',
    shutter: '1/200s',
    sub: 'Pose hangat pasangan muda di studio foto monokrom dengan senyum intim dan remote clicker nirkabel',
    imageUrl: '/images/pasangan_couple.jpg',
    type: 'pasangan_couple',
  },
  {
    id: 'pose-6',
    name: 'Wisuda & Kelulusan',
    tag: 'WISUDA / 006',
    lens: '35mm Low-Angle Studio',
    iso: 'ISO 100',
    shutter: '1/250s',
    sub: 'Potret bangga wisudawan bertoga memegang tabung ijazah dengan sudut perspektif studio megah dan berwibawa',
    imageUrl: '/images/wisuda_grad.jpg',
    type: 'wisuda_grad',
  },
]

export const BW_SERVICES = [
  {
    tag: 'SOLO',
    title: 'SELF\nPHOTO',
    titleDetail: 'Solo Shutter Clicker',
    sub: 'Foto sendiri sesuka hati tanpa canggung.',
    desc: 'Pegang remote shutter nirkabel, tentukan pose favoritmu di depan cermin dua arah dengan pencahayaan profesional monokrom.',
    detailSub: 'Potret solo berkarakter dengan remote clicker nirkabel dan perspektif kamera studio berkedalaman.',
    bg: '#111111',
    textColor: '#FFFFFF',
    badgeColor: '#0040FF',
    highlight: 'Gaya Bebas + Semua File Digital',
    lens: '35mm Wide Studio',
    iso: 'ISO 100',
    time: '15 Menit',
    shutter: '1/250s',
    imageUrl: '/images/self_photo.jpg',
    type: 'self_photo',
  },
  {
    tag: 'BESTIES',
    title: 'BARENG\nTEMAN',
    titleDetail: 'Duo Besties Hangout',
    sub: 'Sahabat, pasangan, atau geng seru.',
    desc: 'Studio luas ber-AC muat hingga 6 orang. Abadikan momen candid tawa lepas bareng sahabat tanpa gangguan fotografer.',
    detailSub: 'Pose ceria sahabat berdampingan dengan senyum hangat, peace sign, dan sudut pandang wide-angle.',
    bg: '#181818',
    textColor: '#FFFFFF',
    badgeColor: '#00D26A',
    highlight: 'Kapasitas s/d 6 Orang + Properti Bebas',
    lens: '28mm Wide-Angle',
    iso: 'ISO 200',
    time: '20 Menit',
    shutter: '1/200s',
    imageUrl: '/images/bareng_teman.jpg',
    type: 'bareng_teman',
  },
  {
    tag: 'BOOTH',
    title: 'PHOTO\nBOOTH',
    titleDetail: 'Bilik Photobooth Squad',
    sub: 'Photostrip & potret candid seru untuk acaramu.',
    desc: 'Bilik photobooth dengan cetak kilat instan 15 detik, frame strip minimalis hitam-putih, barcode download digital.',
    detailSub: 'Pose riang tiga sahabat di bilik photobooth dengan kacamata retro dan photostrip instan.',
    bg: '#0F172A',
    textColor: '#FFFFFF',
    badgeColor: '#38BDF8',
    highlight: 'Cetak Kilat 15 Detik + Pose Bebas',
    lens: '24mm Photobooth Lens',
    iso: 'ISO 400',
    time: 'Instant Print',
    shutter: '1/320s',
    imageUrl: '/images/photobooth.jpg',
    type: 'photobooth',
  },
  {
    tag: 'CONCEPT',
    title: 'CREATIVE\nSHOOT',
    titleDetail: 'Artistic Editorial Shoot',
    sub: 'Sesi foto konsep dengan sudut perspektif artistik.',
    desc: 'Eksplorasi sudut pandang unik seperti low-angle, wide-angle fisheye, atau high-angle studio untuk portofolio dan konten estetik.',
    detailSub: 'Eksplorasi potret editorial artistik berperspektif high-angle dengan pencahayaan softbox studio.',
    bg: '#000000',
    textColor: '#FFFFFF',
    badgeColor: '#F59E0B',
    highlight: 'Arahan Sudut Artistik + Lighting Khusus',
    lens: '35mm High-Angle Studio',
    iso: 'ISO 100',
    time: '30 Menit',
    shutter: '1/500s',
    imageUrl: '/images/creative_shoot.jpg',
    type: 'creative_shoot',
  },
  {
    tag: 'COUPLE',
    title: 'PASANGAN\n& PREWED',
    titleDetail: 'Romantic Duo Portrait',
    sub: 'Momen intim berdua penuh kehangatan tanpa rasa canggung.',
    desc: 'Sesi foto romantis bareng pasangan untuk anniversary, date seru, atau pre-wedding kasual dengan pencahayaan hangat dan shutter mandiri.',
    detailSub: 'Potret romantis berdua dengan remote clicker nirkabel, rangkulan santai, dan perspektif studio yang intim.',
    bg: '#1A1515',
    textColor: '#FFFFFF',
    badgeColor: '#EC4899',
    highlight: 'Sesi Intim Berdua + Semua File Digital',
    lens: '50mm Studio Portrait',
    iso: 'ISO 100',
    time: '20 Menit',
    shutter: '1/200s',
    imageUrl: '/images/pasangan_couple.jpg',
    type: 'pasangan_couple',
  },
  {
    tag: 'WISUDA',
    title: 'WISUDA &\nKELULUSAN',
    titleDetail: 'Milestone Academic Portrait',
    sub: 'Abadikan toga kebanggaan & pencapaian kelulusanmu.',
    desc: 'Rayakan momen kelulusan kuliah atau sekolah bersama toga, buket bunga, dan tabung ijazah dengan arahan pencahayaan studio bernuansa bangga.',
    detailSub: 'Potret bangga wisudawan bertoga memegang tabung ijazah dengan perspektif low-angle studio yang megah dan berwibawa.',
    bg: '#131A1D',
    textColor: '#FFFFFF',
    badgeColor: '#8B5CF6',
    highlight: 'Sedia Jubah Toga + Cetak Frame Kilat',
    lens: '35mm Low-Angle Studio',
    iso: 'ISO 100',
    time: '25 Menit',
    shutter: '1/250s',
    imageUrl: '/images/wisuda_grad.jpg',
    type: 'wisuda_grad',
  },
]

